import { QueryResult } from '../types';

export type ExportFormat = 'csv' | 'json' | 'sql' | 'excel';

export interface ExportOptions {
  format: ExportFormat;
  includeHeaders: boolean;
  delimiter: string;
  tableName?: string;
}

export function exportToCSV(result: QueryResult, options: ExportOptions): string {
  const { columns, rows } = result;
  const { delimiter = ',', includeHeaders = true } = options;
  
  const escapeValue = (value: any): string => {
    const str = String(value ?? '');
    if (str.includes(delimiter) || str.includes('"') || str.includes('\n')) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };
  
  let output = '';
  
  if (includeHeaders) {
    output += columns.map(escapeValue).join(delimiter) + '\n';
  }
  
  for (const row of rows) {
    output += row.map(escapeValue).join(delimiter) + '\n';
  }
  
  return output;
}

export function exportToJSON(result: QueryResult): string {
  const { columns, rows } = result;
  
  const data = rows.map((row) => {
    const obj: Record<string, any> = {};
    columns.forEach((col, idx) => {
      obj[col] = row[idx];
    });
    return obj;
  });
  
  return JSON.stringify(data, null, 2);
}

export function exportToSQL(result: QueryResult, options: ExportOptions): string {
  const { columns, rows } = result;
  const tableName = options.tableName || 'exported_table';
  
  if (rows.length === 0) {
    return `-- No data to export\n`;
  }
  
  let output = `-- Export for table: ${tableName}\n`;
  output += `-- Rows: ${rows.length}\n`;
  output += `-- Generated by DataGrip Alternative\n\n`;
  
  for (const row of rows) {
    const values = row.map((value) => {
      if (value === null) return 'NULL';
      if (typeof value === 'number') return String(value);
      if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
      return `'${String(value).replace(/'/g, "''")}'`;
    });
    
    output += `INSERT INTO ${tableName} (${columns.map(c => `"${c}"`).join(', ')}) VALUES (${values.join(', ')});\n`;
  }
  
  return output;
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportResult(result: QueryResult, options: ExportOptions, filename?: string): void {
  const { format } = options;
  let content: string;
  let extension: string;
  let mimeType: string;
  
  switch (format) {
    case 'csv':
      content = exportToCSV(result, options);
      extension = 'csv';
      mimeType = 'text/csv;charset=utf-8;';
      break;
    case 'json':
      content = exportToJSON(result);
      extension = 'json';
      mimeType = 'application/json;charset=utf-8;';
      break;
    case 'sql':
      content = exportToSQL(result, options);
      extension = 'sql';
      mimeType = 'text/plain;charset=utf-8;';
      break;
    case 'excel':
      content = exportToCSV(result, { ...options, delimiter: '\t' });
      extension = 'tsv';
      mimeType = 'text/tab-separated-values;charset=utf-8;';
      break;
    default:
      throw new Error(`Unsupported export format: ${format}`);
  }
  
  const name = filename || `export_${Date.now()}.${extension}`;
  downloadFile(content, name, mimeType);
}
